version: 2
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
exclude_patterns:
  - "__tests__/"
  - "node_modules/"
  - "docs/"
  - "scripts/"
  - "client/src/index.js"
  - "client/src/serviceWorker.js"
  - "client/src/containers/CrawlGraph/react-d3-tree-modified/"
